{
 "title": "OVH S3 Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Incoming Bandwidth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "gbytes", "label": "GiB" }
   ],
   "targets": [
    { "expr": "ovh_s3_incoming_bandwidth", "legendFormat": "{{region}} - {{bucket}}" }
   ]
  },
  {
   "title": "Outgoing Bandwidth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "gbytes", "label": "GiB" }
   ],
   "targets": [
    { "expr": "ovh_s3_outgoing_bandwidth", "legendFormat": "{{region}} - {{bucket}}" }
   ]
  },
  {
   "title": "Incoming Internal Bandwidth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "gbytes", "label": "GiB" }
   ],
   "targets": [
    {
     "expr": "ovh_s3_incoming_internal_bandwidth",
     "legendFormat": "{{region}} - {{bucket}}"
    }
   ]
  },
  {
   "title": "Outgoing Internal Bandwidth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "gbytes", "label": "GiB" }
   ],
   "targets": [
    {
     "expr": "ovh_s3_outgoing_internal_bandwidth",
     "legendFormat": "{{region}} - {{bucket}}"
    }
   ]
  },
  {
   "title": "Stored Data",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "gbytes", "label": "GiBh" }
   ],
   "targets": [
    { "expr": "ovh_s3_stored", "legendFormat": "{{region}} - {{bucket}}" }
   ]
  },
  {
   "title": "Total Billed Price",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "currencyEUR", "label": "EUR" }
   ],
   "targets": [
    { "expr": "ovh_s3_total_price", "legendFormat": "{{region}} - {{bucket}}" }
   ]
  },
  {
   "title": "Objects Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    { "expr": "ovh_s3_objects_count", "legendFormat": "{{region}} - {{bucket}}" }
   ]
  },
  {
   "title": "Objects Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes" }
   ],
   "targets": [
    { "expr": "ovh_s3_objects_size", "legendFormat": "{{region}} - {{bucket}}" }
   ]
  }
 ]
}